import PDFDocument from "pdfkit";
import type { StoredAnalysisRecord } from "../db/analysis-session-store";

export async function generateForensicReportPdf(
  record: StoredAnalysisRecord
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];

    const doc = new PDFDocument({
      size: "A4",
      margin: 48,
      info: {
        Title: `Cipher Sleuth Report ${record.analysisId}`,
        Author: "Cipher Sleuth",
        Subject: "Digital Image Forensic Report",
      },
    });

    doc.on("data", (chunk: Buffer) => chunks.push(chunk));
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);

    doc.fontSize(20).text("Cipher Sleuth Forensic Report");
    doc.moveDown(0.5);
    doc.fontSize(10).fillColor("#444").text(`Analysis ID: ${record.analysisId}`);
    doc.text(`Generated At: ${record.generatedAt}`);
    doc.text(`Original Filename: ${record.filenameOriginal}`);
    doc.text(`SHA-256: ${record.fileHashSha256}`);

    doc.moveDown(1);
    doc.fillColor("#000").fontSize(14).text("Final Assessment");
    doc.moveDown(0.3);
    doc.fontSize(11).text(`Trust Score: ${record.finalTrustScore}/100`);
    doc.text(`Verdict: ${record.forensicBreakdown.verdictLabel}`);
    doc.text(
      `Scoring Model: ${record.trustScoreBreakdown.scoringModel} (Weighted Penalty ${record.trustScoreBreakdown.weightedPenaltyScore})`
    );

    doc.moveDown(1);
    doc.fontSize(14).text("Executive Summary");
    doc.moveDown(0.3);
    doc.fontSize(11).text(record.forensicBreakdown.executiveSummary, {
      align: "left",
    });

    doc.moveDown(1);
    doc.fontSize(14).text("Orchestrator Risk Signals");
    doc.moveDown(0.3);
    doc.fontSize(11);
    for (const signal of record.forensicBreakdown.orchestrator.riskSignals) {
      doc.text(`- ${signal}`);
    }

    doc.moveDown(1);
    doc.fontSize(14).text("Agent Summary");
    doc.moveDown(0.3);
    doc.fontSize(11);
    for (const agent of record.forensicBreakdown.agentFindings) {
      doc.text(
        `- ${agent.agentName} | delta ${agent.trustDelta} | confidence ${agent.confidence} | ${agent.keyFinding}`
      );
    }

    doc.moveDown(1);
    doc.fontSize(14).text("Scoring Contributions");
    doc.moveDown(0.3);
    doc.fontSize(11);
    for (const item of record.trustScoreBreakdown.perAgent) {
      doc.text(
        `- ${item.agentId}: raw=${item.rawPenalty}, normalized=${item.normalizedPenalty}, weight=${item.weight}, weighted=${item.weightedPenaltyContribution}`
      );
    }

    doc.moveDown(1);
    doc.fontSize(9).fillColor("#555").text(
      "Read-only forensic export generated by Cipher Sleuth. No interactive form fields are embedded.",
      { align: "left" }
    );

    doc.end();
  });
}
